name: NASA Project CI
# on: 何時會觸發
on:
  push:
    # 可以指定監控多個分支
    branches: [ main ]
  pull_request:
    branches: [ main ]
# jobs 預設會同時進行，如果有相依性要額外設定 needs
jobs: 
  build:
    # runs-on 指定 os
    runs-on: ubuntu-latest
    # 指定要跑的 actions (list)
    steps:
      # 有許多已經寫好的 action 可以使用，@指定版本
      - uses: actions/checkout@v2
      # 除了直接使用 uses ，也可以使用 name 取名
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
      # with 對於 actions 給予一些參數
        with:
          node-version:
      - run: npm install
      - run: npm run build --prefix client

  # 會在 build 執行完才做
  # deploy:
  #   needs: build