name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
    env:
      # 前端的框架會偵測 CI 這個變數
      # 在 test 就不會進入 watch mode
      CI: true
    strategy:
    # martix 可以指定多個版本來測試，並且會同時進行
      martix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # name 也可以使用變數帶入
      - name: Use Node.js version 16 ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
        # 使用 {{}} 來指定上面的變數
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
